name: HACS Validation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: HACS Action
        uses: hacs/action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

